server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/database?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8

woi:
  woim:
    #如果使用的是SnowflakeIdGenerator，在使用集群时需要配置下datacenter-id和machine-id（或只需配置machine-id）
    datacenter-id: 0
    machine-id: 0
    #配置集群（前提你使用的是DefaultAgent进行分布式的远程调用，如果自定义Agent则可以忽略，并自己实现分布式逻辑）
    server-addr: 127.0.0.1:8081,127.0.0.1:8082
    #连接监听端口
    connection-port: 6666
logging:
  level:
    zone:
      czh:
        woi:
          woim: debug


